### ISSUE TITLE
Collaboration question

### ISSUE THREAD

**Issue by hictooth** [SkySwimmer/Edge#1]
Heyo!
Nice to see this project. I’m working with a couple of others also on a School of Dragons replacement server, wondered if you wanted to work together? To save wasted/duplicated work? We have login/registration/profile creation currently working. If you have discord that’s where we’re currently working, I’m username `hictooth`.

**Comment by SkySwimmer** [comment]
hi um, do you have discord? i feel more comfortable talking there, im in the fer.ever discord if you happen to be there too

personally i would like to keep it like, two projects if you dont mind, but willing to share research etc, i feel more comfortable talking in discord tho, is it possible to continue our conversation there?

(my discord user is Ven'zu'era#7677)

edit: i read over you having a discord sorry- sent a friend request

**Comment by SkySwimmer** [comment]
im really happy to see another emu in the works!

**Comment by SkySwimmer** [comment]
also i noticed you havent implemented a modification system for the DWADragonsMain.xml file yet, you can find the code that re-encrypts the manifest of Edge in [ApplicationManifestPreProcessor.java](https://github.com/SkySwimmer/Edge/blob/main/src/contentserver/src/main/java/org/asf/edge/contentserver/http/postprocessors/ApplicationManifestPreProcessor.java)

the encryption key the client uses is the MD5 hash of `C92EC1AA-54CD-4D0C-A8D5-403FCCF1C0BD` for all platforms of version 3.31.0, the DWADragonsMain xml defines all endpoints of the game, replace that with a custom asset server and all traffic can be redirected to your server without the need of mitmproxy, the client uses 3DES with ASCII encoding for key and xml file, result is encoded in base64

**Comment by SkySwimmer** [comment]
AAA DIDNT SEE YOU HAD A DISCORD SORRY I FEEL SO SILLY, lemme friend request you rq

**Comment by Joey743** [comment]
I also sent a request, I'm somewhat involved with this and would be interested in being part of discussions
